### ISSUE TITLE
Proposal for a few improvements

### ISSUE THREAD

**Issue by bbenoit** [grafov/plantuml2mysql#1]
Hello,

I found your script very useful and enjoyed using it.
The constraints it imposes are not a problem, but I'd like to add a few features:
- use a line starting with "`..`" or "`__`" to insert a separator in a class / table description, and ignore it when generating SQL code;
- use HTML tags in comments (I use italic to emphasis them in the graphical view), and remove them in the SQL code;
- avoid conflict with reserved words in mySQL (mySQL behaviour with my "`Client`" table confused me);
- add a time-stamp and original file name at the top of the generated SQL code;
- add a minimal help and guide for users

My small contributions are grouped into the patch file enclosed:

[plantuml2mysql.bbenoit.20160520.patch.txt](https://github.com/grafov/plantuml2mysql/files/275021/plantuml2mysql.bbenoit.20160520.patch.txt)

Please let me know if you need more information about the code above.

Regards,
-\- 
Benoît Bailleux

**Comment by grafov** [comment]
Nice addition, thank you! I will merge your patch tomorrow. But may be better if you fork the repository and make a pull request? Then it will show you as author of this contribution.

**Comment by bbenoit** [comment]
Thank you.
Forking + doing a pull request is definitely a good idea.
I'll will do that tomorrow or Monday, if you don't mind waiting a bit.

Regards,
-\- 
Benoît

**Comment by grafov** [comment]
Good, I'll wait your pull request.

**Comment by grafov** [comment]
Realized in PR #2. Thank you!
